markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Django Wong
host: blog.36coder.com
desc: Some description of your site.

custom:
    category:
        study: 学习心得
        python: Python学习
        golang: Golang学习
    categories:
      - name:  study
        title: 学习心得
		
      - name:  python
        title: Python学习
		
      - name: golang
        title: Golang学习

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Django Wong
        email: rlk002@gmail.com
        disqus: assad2012githubio              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: assad2012                # GitHub账号
        gravatar: 868bf0ae25e5334c4493a050970611b5  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
